name: AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

permissions:
  contents: read

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, triloamd01]
    steps:
      - name: echo "hello world"
        run: |
          while true; do
            date=$(date +"%H:%M:%S")
            echo Current date is $date
            sleep 1
          done