name: AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gcc:
    runs-on: [self-hosted, at2_runner0]
    uses:
      ./.github/workflows/intel.yml
  intel:
    runs-on: [self-hosted, at2_runner0]
    uses:
      ./.github/workflows/gcc.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo "hello world"
        run: |
          echo "hello world"