name: pr-test-AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types: 
      - submitted
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  triloamd01-gcc:
    runs-on: [self-hosted, triloamd01]
    if: ${{ github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.review.state == 'APPROVED' }}
    steps:
      - name: Clone trilinos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show output pass
        run: |
          ./test-pass.sh
      - name: show output fail
        continue-on-error: true
        run: |
          ./test-fail.sh
      - name: mask output pass
        run: |
          OUTPUT=$(./test-pass.sh)
          echo "::add-mask::$OUTPUT"
      - name: mask output fail
        continue-on-error: true
        run: |
          OUTPUT=$(./test-fail.sh)
          echo "::add-mask::$OUTPUT"
      - name: file write test
        continue-on-error: true
        run: |
          OUTPUT_0=$(bash -l -c "OUTPUT_1=$(./test-file-write.sh)" 2>&1)
          echo "::add-mask::$OUTPUT"
          ls -l
      - name: real world trilinos example
        working-directory: ./packages/framework
        run: |
          OUTPUT_0=$(bash -l -c "OUTPUT_1=$(./get_dependencies.sh --container)" 2>&1)
          echo "::add-mask::$OUTPUT_0"
          echo "::add-mask::$OUTPUT_1"