name: pr-test-AT2

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types: 
      - submitted
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  triloamd01-gcc:
    runs-on: [self-hosted, triloamd01]
    if: ${{ github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.review.state == 'APPROVED' }}
    steps:
      - name: Clone trilinos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get dependencies
        working-directory: ./packages/framework
        run: |
          bash -l -c "./get_dependencies.sh --container"
      - name: get dependencies
        working-directory: ./packages/framework
        run: |
          bash -l -c "./get_dependencies.sh --container"
          bash -l -c "echo ::add-mask::./get_dependencies.sh --container"
      - name: get dependencies
        working-directory: ./packages/framework
        run: |
          echo "./get_dependencies.sh --container"
          echo "::add-mask::./get_dependencies.sh --container"